# Generated by Django 6.0.5 on 2026-05-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrowserVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField()),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_logs', to='tracker.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AppUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(max_length=500)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_logs', to='tracker.machine')),
            ],
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=500)),
                ('pages', models.PositiveIntegerField()),
                ('printed_at', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='tracker.machine')),
            ],
        ),
    ]
