# Generated by Django 6.0.5 on 2026-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
